# temporary placeholder that'll just invoke C:\f\build.cmd
buildscript:
  stage: build
  script:
    - "C:\\f\\build.cmd"

cache:
  untracked: true
  paths:
    - bin/
    - build/
    - shared/citversion.h